- shell:
    - command: yay -Syu
      stdout: true
      stderr: true
      stdin: true
# Prerequisites for neovim
    - command: yay -Sy base-devel cmake unzip ninja tree-sitter curl
      stdout: true
      stderr: true
      stdin: true
