- shell:
    - command: yay -Syu
      stdout: true
      stderr: true
      stdin: true
    - command: yay -Sy --needed base-devel zsh cmake unzip ninja tree-sitter curl ripgrep navi jq dunst neovim nvim-packer-git
      stdout: true
      stderr: true
      stdin: true
