[ -f ~/.env ] && source ~/.env
export TERM="xterm-256color"
export SHELL="zsh"

if [ -f ~/.profile ]; then source ~/.profile; fi
if [ -f ~/.profile_env ]; then source ~/.profile_env; fi

if [ -f ~/.cache/wal/sequences ]; then (cat ~/.cache/wal/sequences &); fi

autoload -Uz bashcompinit && bashcompinit
autoload -Uz compinit && compinit
# Load plugins
source ~/.antidote/antidote.zsh

antidote load

# starship
eval "$(starship init zsh)"

# aliases
alias gaa="git add ."
alias gc="git commit"
alias ls="ls --color=auto"
alias l="colorls -A --sd"
alias ll="colorls -lA --sd"
alias dcu="docker compose up -d"
alias dcd="docker compose down"
alias dce="docker compose exec"
alias dcr="docker compose restart"

# --- Colored LESS E.G for man ---
export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'

# no beep bop boup
unsetopt BEEP

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
# bindkey -e
# End of lines configured by zsh-newuser-install

export ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor root line)
export ZSH_HIGHLIGHT_PATTERNS=('rm *\*' 'fg=white,bold,bg=red')

if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
	source /etc/profile.d/vte.sh
fi

fzf-git-branch() {
    git rev-parse HEAD > /dev/null 2>&1 || return

    git branch --color=always --all --sort=-committerdate |
        grep -v HEAD |
        fzf --height 50% --ansi --no-multi --preview-window right:65% \
            --preview 'git log -n 50 --color=always --date=short --pretty="format:%C(auto)%cd %h%d %s" $(sed "s/.* //" <<< {})' |
        sed "s/.* //"
}

fzf-git-checkout() {
    git rev-parse HEAD > /dev/null 2>&1 || return

    local branch

    branch=$(fzf-git-branch)
    if [[ "$branch" = "" ]]; then
        echo "No branch selected."
        return
    fi

    # If branch name starts with 'remotes/' then it is a remote branch. By
    # using --track and a remote branch name, it is the same as:
    # git checkout -b branchName --track origin/branchName
    if [[ "$branch" = 'remotes/'* ]]; then
        git checkout --track $branch
    else
        git checkout $branch;
    fi
}
alias gb='fzf-git-branch'
alias gco='fzf-git-checkout'

ssh-use-key() {
    command="ssh-add $1; ${@:2}"
    ssh-agent zsh -c $command
}

zstyle ':completion:*' menu select
# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
# set descriptions format to enable group support
zstyle ':completion:*:descriptions' format '[%d]'
# set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# preview directory's content with exa when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'exa -1 --color=always $realpath'

# history
bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down

# ctrl-left
bindkey "^[[1;5D" vi-backward-word
# alt-left aka not roussel
bindkey "^[[1;3D" vi-backward-word
# ctrl-right
bindkey "^[[1;5C" vi-forward-word
# alt-right aka facho
bindkey "^[[1;3C" vi-forward-word
# ctrl-backspace
bindkey "^H" vi-backward-kill-word
# ctrl-supp
bindkey "^[[3;5~" delete-word
# supp
bindkey "^[[3~" vi-delete-char
# end
bindkey "^[[F" end-of-line
# beginning
bindkey "^[[H" beginning-of-line

bashcompinit
compinit


# --- Load ASDF version management ---
ASDF_DIR="${ASDF_DIR:-$HOME/.asdf}"
ASDF_COMPLETIONS="$ASDF_DIR/completions"
. "$ASDF_DIR/asdf.sh"
. "$ASDF_COMPLETIONS/asdf.bash"

if [ -z $DISPLAY ] && [ -x "$(command -v startx)" ]; then exec ssh-agent startx; fi
